# Generated by Django 5.0.14 on 2025-12-22 17:20

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Laisser vide pour publier immédiatement, ou définir une date future pour planifier.', null=True, verbose_name='Date de publication')),
                ('meta_title', models.CharField(blank=True, help_text='Titre pour les moteurs de recherche (max 70 caractères)', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, verbose_name='Meta Description')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Titre')),
                ('excerpt', models.TextField(blank=True, help_text="Résumé court de l'article (max 300 caractères)", max_length=300, verbose_name='Extrait')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/featured/', verbose_name='Image principale')),
                ('featured_image_caption', models.CharField(blank=True, max_length=255, verbose_name="Légende de l'image")),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500, verbose_name='Tags')),
                ('content', models.TextField(blank=True, help_text="Contenu HTML de l'article (utilisé si pas de blocs)", verbose_name='Contenu HTML')),
                ('reading_time', models.PositiveIntegerField(default=1, help_text='Temps de lecture estimé en minutes', verbose_name='Temps de lecture')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Afficher dans la section À la Une (US-05)', verbose_name='À la Une')),
                ('is_trending', models.BooleanField(default=False, help_text='Marquer comme article tendance', verbose_name='Tendance')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('block_type', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('quote', 'Citation'), ('video', 'Vidéo'), ('tweet', 'Tweet'), ('heading', 'Titre'), ('list', 'Liste'), ('code', 'Code')], default='text', max_length=20, verbose_name='Type de bloc')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordre')),
                ('content', models.TextField(blank=True, help_text='Contenu textuel du bloc', verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/blocks/', verbose_name='Image')),
                ('image_caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('embed_url', models.URLField(blank=True, help_text='URL YouTube ou Twitter', verbose_name='URL embed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (niveau de titre, langue du code, etc.)', verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': "Bloc d'article",
                'verbose_name_plural': "Blocs d'article",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nom')),
                ('photo', models.ImageField(blank=True, help_text="Photo de l'auteur (format carré recommandé)", null=True, upload_to='authors/photos/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, help_text="Biographie de l'auteur", verbose_name='Biographie')),
                ('email', models.EmailField(blank=True, help_text='Email de contact (optionnel)', max_length=254, verbose_name='Email')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('is_active', models.BooleanField(default=True, help_text="Les auteurs inactifs n'apparaissent pas dans les listes", verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordre')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie', verbose_name='Description')),
                ('color', models.CharField(default='#3B82F6', help_text='Code couleur hexadécimal (ex: #FF5733)', max_length=7, validators=[apps.core.validators.validate_hex_color], verbose_name='Couleur')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: globe, briefcase, cpu)", max_length=50, verbose_name='Icône')),
                ('image', models.ImageField(blank=True, help_text='Image de couverture de la catégorie', null=True, upload_to='categories/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, help_text='Les catégories inactives ne sont pas affichées', verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text="Afficher dans la section vedette de l'accueil", verbose_name='En vedette')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Laisser vide pour publier immédiatement, ou définir une date future pour planifier.', null=True, verbose_name='Date de publication')),
                ('meta_title', models.CharField(blank=True, help_text='Titre pour les moteurs de recherche (max 70 caractères)', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, verbose_name='Meta Description')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Description de la vidéo', verbose_name='Description')),
                ('youtube_url', models.URLField(help_text='URL de la vidéo YouTube', validators=[apps.core.validators.validate_youtube_url], verbose_name='URL YouTube')),
                ('thumbnail', models.ImageField(blank=True, help_text='Laisser vide pour utiliser la miniature YouTube', null=True, upload_to='videos/thumbnails/', verbose_name='Miniature personnalisée')),
                ('youtube_thumbnail', models.URLField(blank=True, help_text='URL de la miniature YouTube (auto-générée)', verbose_name='Miniature YouTube')),
                ('video_type', models.CharField(choices=[('emission', 'Émission'), ('reportage', 'Reportage'), ('interview', 'Interview'), ('documentary', 'Documentaire'), ('short', 'Court métrage')], db_index=True, default='reportage', max_length=20, verbose_name='Type de vidéo')),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500, verbose_name='Tags')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Durée de la vidéo en secondes', verbose_name='Durée (secondes)')),
                ('youtube_id', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='ID YouTube')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Marquer comme vidéo en vedette (US-03)', verbose_name='En vedette')),
                ('is_live', models.BooleanField(default=False, help_text='Marquer comme diffusion en direct', verbose_name='En direct')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
