# Generated by Django 5.0.14 on 2025-12-22 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editorial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_articles', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_articles', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='articleblock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='editorial.article', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur lié'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='editorial.author', verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='editorial.category', verbose_name='Catégorie parente'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='editorial.category', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='editorial.category', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='video',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_videos', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='editorial_a_status_1518b6_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured', 'status'], name='editorial_a_is_feat_c1a3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='editorial_a_categor_5bd752_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', 'published_at'], name='editorial_v_status_43cb16_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_featured', 'status'], name='editorial_v_is_feat_5d3208_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['video_type', 'status'], name='editorial_v_video_t_68465e_idx'),
        ),
    ]
