# Generated by Django 5.0.14 on 2025-12-22 18:47

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('text', 1), ('image', 5), ('quote', 9), ('video', 11), ('tweet', 13), ('heading', 16), ('list', 20), ('code', 23), ('cta', 27)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Contenu'}), 1: ('wagtail.blocks.StructBlock', [[('content', 0)]], {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Crédit photo', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('attribution', 4)]], {}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Citation'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Auteur', 'max_length': 255, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Source', 'max_length': 255, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('quote', 6), ('author', 7), ('source', 8)]], {}), 10: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': "Collez l'URL YouTube, Vimeo ou autre", 'label': 'URL de la vidéo'}), 11: ('wagtail.blocks.StructBlock', [[('video', 10), ('caption', 3)]], {}), 12: ('wagtail.blocks.URLBlock', (), {'help_text': "Collez l'URL du tweet (ex: https://twitter.com/user/status/123)", 'label': 'URL du Tweet'}), 13: ('wagtail.blocks.StructBlock', [[('tweet_url', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2 - Titre principal'), ('h3', 'H3 - Sous-titre'), ('h4', 'H4 - Petit titre')], 'label': 'Niveau'}), 16: ('wagtail.blocks.StructBlock', [[('heading', 14), ('level', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Élément'}), 18: ('wagtail.blocks.ListBlock', (17,), {'label': 'Éléments de la liste'}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('ul', 'Liste à puces'), ('ol', 'Liste numérotée')], 'label': 'Type de liste'}), 20: ('wagtail.blocks.StructBlock', [[('items', 18), ('list_type', 19)]], {}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash'), ('json', 'JSON'), ('other', 'Autre')], 'label': 'Langage'}), 22: ('wagtail.blocks.TextBlock', (), {'label': 'Code'}), 23: ('wagtail.blocks.StructBlock', [[('language', 21), ('code', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du bouton'}), 25: ('wagtail.blocks.URLBlock', (), {'label': 'Lien'}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Principal (bleu)'), ('secondary', 'Secondaire (gris)'), ('success', 'Succès (vert)')], 'label': 'Style'}), 27: ('wagtail.blocks.StructBlock', [[('text', 24), ('url', 25), ('style', 26)]], {})}, help_text='Composez votre article avec les blocs disponibles', null=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Ancien contenu HTML - utilisez le champ "Contenu" ci-dessus', verbose_name='Contenu HTML (legacy)'),
        ),
    ]
