# Generated by Django 5.0.14 on 2025-12-24 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0003_article_body_alter_article_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="external_image_url",
            field=models.URLField(
                blank=True,
                help_text="URL d'une image externe (ex: Unsplash). Utilisé si pas d'image uploadée.",
                verbose_name="URL image externe",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_trending", "status"], name="editorial_a_is_tren_64d7f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["author", "status"], name="editorial_a_author__34a9e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["is_live", "status"], name="editorial_v_is_live_402da8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["category", "status"], name="editorial_v_categor_9fa055_idx"
            ),
        ),
    ]
