# Generated by Django 5.0.14 on 2026-02-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0004_add_external_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="linkedin",
            field=models.URLField(
                blank=True, default="", null=True, verbose_name="LinkedIn"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="twitter",
            field=models.URLField(
                blank=True, default="", null=True, verbose_name="Twitter/X"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="website",
            field=models.URLField(
                blank=True, default="", null=True, verbose_name="Site web"
            ),
        ),
    ]
