# Generated by Django 5.0.14 on 2025-12-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('replied', 'Répondu'), ('archived', 'Archivé')], default='new', max_length=20, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('unsubscribed', 'Désabonné')], default='pending', max_length=20, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('source', models.CharField(blank=True, help_text="Page ou formulaire d'origine", max_length=100, verbose_name='Source')),
                ('external_id', models.CharField(blank=True, help_text='ID dans Brevo/Mailchimp', max_length=100, verbose_name='ID externe')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation')),
                ('sync_error', models.TextField(blank=True, verbose_name='Erreur de synchronisation')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de désabonnement')),
            ],
            options={
                'verbose_name': 'Inscription newsletter',
                'verbose_name_plural': 'Inscriptions newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
