# Generated by Django 5.0.14 on 2026-03-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('network', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('telegram', 'Telegram'), ('snapchat', 'Snapchat'), ('other', 'Autre')], help_text="Identifiant du réseau (détermine l'icône affichée sur le site)", max_length=30, unique=True, verbose_name='Réseau')),
                ('label', models.CharField(blank=True, help_text='Nom affiché (laisser vide pour utiliser le nom du réseau)', max_length=100, verbose_name='Libellé')),
                ('url', models.URLField(help_text='Ex: https://facebook.com/geniesdafriquemedia', verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour masquer ce réseau sur le site', verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, help_text='0 = en premier', verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Réseau Social',
                'verbose_name_plural': 'Réseaux Sociaux',
                'ordering': ['order', 'network'],
            },
        ),
    ]
