# Generated by Django 5.0.14 on 2025-12-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_articles",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre total d'articles publiés",
                        verbose_name="Total Articles Publiés",
                    ),
                ),
                (
                    "total_videos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre total de vidéos publiées",
                        verbose_name="Total Vidéos Publiées",
                    ),
                ),
                (
                    "monthly_readers",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre de lecteurs uniques par mois",
                        verbose_name="Lecteurs Mensuels",
                    ),
                ),
                (
                    "total_views",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre total de vues de contenu",
                        verbose_name="Vues Totales",
                    ),
                ),
                (
                    "countries_covered",
                    models.PositiveIntegerField(
                        default=54,
                        help_text="Nombre de pays africains couverts",
                        verbose_name="Pays Couverts",
                    ),
                ),
                (
                    "tv_experts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre d'experts et contributeurs TV",
                        verbose_name="Experts TV",
                    ),
                ),
                (
                    "total_authors",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre total d'auteurs actifs",
                        verbose_name="Total Auteurs",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière Mise à Jour"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Seul un enregistrement peut être actif",
                        verbose_name="Actif",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Plateforme",
                "verbose_name_plural": "KPIs Plateforme",
                "ordering": ["-last_updated"],
            },
        ),
    ]
