# Generated by Django 5.0.14 on 2025-12-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformkpi",
            name="countries_covered",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Nombre de pays africains couverts",
                verbose_name="Pays Couverts",
            ),
        ),
    ]
