# Generated by Django 5.0.14 on 2026-03-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="advertisement",
            new_name="advertising_positio_787c65_idx",
            old_name="advertising_positio_idx",
        ),
        migrations.RenameIndex(
            model_name="advertisement",
            new_name="advertising_is_acti_21c01c_idx",
            old_name="advertising_is_acti_idx",
        ),
    ]
