"""
Core Constants - Constantes partagées
"""

# Liste des 54 pays d'Afrique (noms français et anglais courants pour le matching)
AFRICAN_COUNTRIES = {
    'afrique du sud', 'south africa',
    'algérie', 'algeria',
    'angola',
    'bénin', 'benin',
    'botswana',
    'burkina faso',
    'burundi',
    'cameroun', 'cameroon',
    'cap-vert', 'cape verde', 'cabo verde',
    'centrafrique', 'république centrafricaine', 'central african republic',
    'comores', 'comoros',
    'congo', 'république du congo', 'republic of the congo',
    'congo rdc', 'rdc', 'république démocratique du congo', 'dr congo', 'drc',
    'côte d\'ivoire', 'ivory coast',
    'djibouti',
    'égypte', 'egypt',
    'érythrée', 'eritrea',
    'eswatini', 'swaziland',
    'éthiopie', 'ethiopia',
    'gabon',
    'gambie', 'gambia',
    'ghana',
    'guinée', 'guinea',
    'guinée-bissau', 'guinea-bissau',
    'guinée équatoriale', 'equatorial guinea',
    'kenya',
    'lesotho',
    'libéria', 'liberia',
    'libye', 'libya',
    'madagascar',
    'malawi',
    'mali',
    'maroc', 'morocco',
    'maurice', 'mauritius',
    'mauritanie', 'mauritania',
    'mozambique',
    'namibie', 'namibia',
    'niger',
    'nigéria', 'nigeria',
    'ouganda', 'uganda',
    'rwanda',
    'sao tomé-et-principe', 'sao tome and principe',
    'sénégal', 'senegal',
    'seychelles',
    'sierra leone',
    'somalie', 'somalia',
    'soudan', 'sudan',
    'soudan du sud', 'south sudan',
    'tanzanie', 'tanzania',
    'tchad', 'chad',
    'togo',
    'tunisie', 'tunisia',
    'zambie', 'zambia',
    'zimbabwe'
}
